export const FetchMoviesActionTypes = {
  FETCH_MOVIES_LIST: 'FETCH_MOVIES_LIST',
  FETCH_MOVIES_LIST_START: 'FETCH_MOVIES_LIST_START',
  FETCH_MOVIES_LIST_FINISH: 'FETCH_MOVIES_LIST_FINISH'
} as const;